//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.16 at 01:51:18 PM CET 
//


package eu.europa.ec.fisheries.uvms.asset.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssetIdTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AssetIdTypeEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="INTERNAL_ID"/&gt;
 *     &lt;enumeration value="CFR"/&gt;
 *     &lt;enumeration value="IRCS"/&gt;
 *     &lt;enumeration value="IMO"/&gt;
 *     &lt;enumeration value="MMSI"/&gt;
 *     &lt;enumeration value="GUID"/&gt;
 *     &lt;enumeration value="ICCAT"/&gt;
 *     &lt;enumeration value="UVI"/&gt;
 *     &lt;enumeration value="GFCM"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AssetIdTypeEnum", namespace = "enums.asset.fisheries.ec.europa.eu")
@XmlEnum
public enum AssetIdTypeEnum {

    INTERNAL_ID,
    CFR,
    IRCS,
    IMO,
    MMSI,
    GUID,
    ICCAT,
    UVI,
    GFCM;

    public String value() {
        return name();
    }

    public static AssetIdTypeEnum fromValue(String v) {
        return valueOf(v);
    }

}
