//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.16 at 01:51:18 PM CET 
//


package eu.europa.ec.fisheries.uvms.asset.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for AssetListCriteria complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssetListCriteria"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isDynamic" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="criterias" type="{types.asset.wsdl.fisheries.ec.europa.eu}AssetListCriteriaPair" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssetListCriteria", propOrder = {
    "isDynamic",
    "criterias"
})
public class AssetListCriteria implements Equals, HashCode
{

    protected Boolean isDynamic;
    protected List<AssetListCriteriaPair> criterias;

    /**
     * Default no-arg constructor
     * 
     */
    public AssetListCriteria() {
        super();
    }

    /**
     * Fully-initialising value constructor
     * 
     */
    public AssetListCriteria(final Boolean isDynamic, final List<AssetListCriteriaPair> criterias) {
        this.isDynamic = isDynamic;
        this.criterias = criterias;
    }

    /**
     * Gets the value of the isDynamic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDynamic() {
        return isDynamic;
    }

    /**
     * Sets the value of the isDynamic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDynamic(Boolean value) {
        this.isDynamic = value;
    }

    /**
     * Gets the value of the criterias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the criterias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCriterias().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssetListCriteriaPair }
     * 
     * 
     */
    public List<AssetListCriteriaPair> getCriterias() {
        if (criterias == null) {
            criterias = new ArrayList<AssetListCriteriaPair>();
        }
        return this.criterias;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof AssetListCriteria)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final AssetListCriteria that = ((AssetListCriteria) object);
        {
            Boolean lhsIsDynamic;
            lhsIsDynamic = this.isIsDynamic();
            Boolean rhsIsDynamic;
            rhsIsDynamic = that.isIsDynamic();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "isDynamic", lhsIsDynamic), LocatorUtils.property(thatLocator, "isDynamic", rhsIsDynamic), lhsIsDynamic, rhsIsDynamic)) {
                return false;
            }
        }
        {
            List<AssetListCriteriaPair> lhsCriterias;
            lhsCriterias = (((this.criterias!= null)&&(!this.criterias.isEmpty()))?this.getCriterias():null);
            List<AssetListCriteriaPair> rhsCriterias;
            rhsCriterias = (((that.criterias!= null)&&(!that.criterias.isEmpty()))?that.getCriterias():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "criterias", lhsCriterias), LocatorUtils.property(thatLocator, "criterias", rhsCriterias), lhsCriterias, rhsCriterias)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            Boolean theIsDynamic;
            theIsDynamic = this.isIsDynamic();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "isDynamic", theIsDynamic), currentHashCode, theIsDynamic);
        }
        {
            List<AssetListCriteriaPair> theCriterias;
            theCriterias = (((this.criterias!= null)&&(!this.criterias.isEmpty()))?this.getCriterias():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "criterias", theCriterias), currentHashCode, theCriterias);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
