//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.16 at 01:51:18 PM CET 
//


package eu.europa.ec.fisheries.uvms.asset.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConfigSearchFieldEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ConfigSearchFieldEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FLAG_STATE"/&gt;
 *     &lt;enumeration value="EXTERNAL_MARKING"/&gt;
 *     &lt;enumeration value="NAME"/&gt;
 *     &lt;enumeration value="IRCS"/&gt;
 *     &lt;enumeration value="CFR"/&gt;
 *     &lt;enumeration value="MMSI"/&gt;
 *     &lt;enumeration value="GUID"/&gt;
 *     &lt;enumeration value="HIST_GUID"/&gt;
 *     &lt;enumeration value="ICCAT"/&gt;
 *     &lt;enumeration value="UVI"/&gt;
 *     &lt;enumeration value="GFCM"/&gt;
 *     &lt;enumeration value="HOMEPORT"/&gt;
 *     &lt;enumeration value="ASSET_TYPE"/&gt;
 *     &lt;enumeration value="LICENSE_TYPE"/&gt;
 *     &lt;enumeration value="PRODUCER_NAME"/&gt;
 *     &lt;enumeration value="IMO"/&gt;
 *     &lt;enumeration value="GEAR_TYPE"/&gt;
 *     &lt;enumeration value="MIN_LENGTH"/&gt;
 *     &lt;enumeration value="MAX_LENGTH"/&gt;
 *     &lt;enumeration value="MIN_POWER"/&gt;
 *     &lt;enumeration value="MAX_POWER"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ConfigSearchFieldEnum", namespace = "enums.asset.fisheries.ec.europa.eu")
@XmlEnum
public enum ConfigSearchFieldEnum {

    FLAG_STATE,
    EXTERNAL_MARKING,
    NAME,
    IRCS,
    CFR,
    MMSI,
    GUID,
    HIST_GUID,
    ICCAT,
    UVI,
    GFCM,
    HOMEPORT,
    ASSET_TYPE,
    LICENSE_TYPE,
    PRODUCER_NAME,
    IMO,
    GEAR_TYPE,
    MIN_LENGTH,
    MAX_LENGTH,
    MIN_POWER,
    MAX_POWER;

    public String value() {
        return name();
    }

    public static ConfigSearchFieldEnum fromValue(String v) {
        return valueOf(v);
    }

}
